### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by Jay-H-C** [DataDog/serilog-sinks-datadog-logs#102]
I am trying to do Agentless logging trying to have a direct upload to Datadog without saving it as a file.
but it does not work, Datadog is waiting for a log forever.

**Comment by gh123man** [comment]
Hi @Jay-H-C 

Can you please provide: 
1. An example of your configuration
2. a copy of any error logs you my have (note: [you may need to configure `exceptionHandler` to catch errors](https://github.com/DataDog/serilog-sinks-datadog-logs#support-configuration-options))
