### ISSUE TITLE
Line number mismatch in exceptions

### ISSUE THREAD

**Issue by alfonsovgs** [DataDog/serilog-sinks-datadog-logs#121]
Hello 👋

I just migrated from Log4Net to Serilog, and when an exception occurs, the line shown is different from the base code:

Datadog shows: 
"System.NullReferenceException: Object reference not set to an instance of an object. << more information >>:line10"

However, line 10 in my code is a return statement or a closing brace }.

**Comment by jszwedko** [comment]
HI @alfonsovgs ,

Did you mean to open this on https://github.com/serilog/serilog ? This plugin is just about forwarding messages logged using Serilog to Datadog but wouldn't be responsible for the exception line number. Unless you have reason to believe it is something this plugin is doing that is causing you to see invalid line numbers? Do you see invalid line numbers using the Serilog file output?

```
using var log = new LoggerConfiguration()
    .WriteTo.Console()
    .WriteTo.File("log.txt")
    .CreateLogger();
```

**Comment by alfonsovgs** [comment]
Hi @jszwedko 
Thank you for your response, I will follow your instructions.

Before using this plugin, I was using the agent to log directly to Datadog, and I didn't encounter this issue. Now, with this plugin, I see this difference in the line numbers.
