### ISSUE TITLE
Wrong config property name

### ISSUE THREAD

**Issue by flavio-cadete-cko** [DataDog/serilog-sinks-datadog-logs#124]
https://github.com/DataDog/serilog-sinks-datadog-logs/releases/tag/v0.5.3

`Renamed logLevel to restrictedMinimumLogLevel in LoggerConfiguration to be consistent with the serilog recommendation. Thanks @tsackey.`

1. This shouldn't be part of minor/patch as it can be considered by some a breaking change
2. Wrong name on the release description, the name is `restrictedToMinimumLevel` not  `restrictedMinimumLogLevel `
https://github.com/DataDog/serilog-sinks-datadog-logs/pull/112

**Comment by jszwedko** [comment]
Thanks @flavio-cadete-cko !

I updated the name in the release description. Looking back, I agree that the option rename is a breaking change. Unfortunately it has already been released, but I updated the release description to make the change clearer. We'll keep a closer eye on this going forward.
