### ISSUE TITLE
Template string interpolation not working in latest release

### ISSUE THREAD

**Issue by garrardkitchen** [DataDog/serilog-sinks-datadog-logs#19]
Dear DD Team,

Since PR #3 (https://github.com/DataDog/serilog-sinks-datadog-logs/pull/3) and latest release, https://github.com/DataDog/serilog-sinks-datadog-logs/issues/5 is no longer fixed.

I've included a screenshot here showing PR #3 producing the last 5 log entries and the latest 0.1.5 producing the other log entries:

![image](https://user-images.githubusercontent.com/993890/51431004-e3e9f980-1c1a-11e9-98cc-855173f520db.png)

This screenshot shows is #5 not working:

![image](https://user-images.githubusercontent.com/993890/51431014-0da32080-1c1b-11e9-8a86-efb5674a1d8c.png)

Warmest regards,

Garrard.

**Comment by achntrl** [comment]
@garrardkitchen, I can't replicate your problem, with the example from the doc

```csharp
public static void Main(string[] args)
        {
            var log = new LoggerConfiguration()
                .WriteTo.DatadogLogs("<API_KEY>")
                .WriteTo.Console()
                .CreateLogger();

            // An example
            var position = new { Latitude = 25, Longitude = 134 };
            var elapsedMs = 34;

            log.Information("Processed {@Position} in {Elapsed:000} ms.", position, elapsedMs);
            System.Threading.Thread.Sleep(10000);
        }
```

![image](https://user-images.githubusercontent.com/6985756/51476284-6a224f00-1d85-11e9-802a-4a01965e3d25.png)

Even if I use the same source/service tags as you. Can you please confirm that you have the 0.1.5 ? A good way of validating this is to change the log line to:

```csharp
log.Warning("Processed {@Position} in {Elapsed:000} ms.", position, elapsedMs);
```

and see if the logs appears as a Warning log on the log explorer

**Comment by garrardkitchen** [comment]
Hi @achntrl , 

Thanks for looking into this!

I've run it again for you.

Here's the log output:

![image](https://user-images.githubusercontent.com/993890/51477375-30027e80-1d80-11e9-9779-fde1ec599194.png)

Here's the binary version (& deps) and sample code:

![image](https://user-images.githubusercontent.com/993890/51477418-532d2e00-1d80-11e9-897e-cd2152b0f026.png)

These are my observations:
 - I'm not seeing the MessageTemplate attribute that is present in your screenshot
 - I'm not writing to the console.

Thanks for helping.

Garrard

**Comment by garrardkitchen** [comment]
Hi @achntrl , 

Thanks for looking into this!

I've run it again for you.

Here's the log output:

![image](https://user-images.githubusercontent.com/993890/51477375-30027e80-1d80-11e9-9779-fde1ec599194.png)

Here's the binary version (& deps) and sample code:

![image](https://user-images.githubusercontent.com/993890/51477700-275e7800-1d81-11e9-9cf7-f74f55b0e1c3.png)

These are my observations:
 - I'm not seeing the MessageTemplate attribute that is present in your screenshot
 - I'm not writing to the console.

Thanks for helping.

Garrard

**Comment by achntrl** [comment]
Hi @garrardkitchen, 

I couldn't replicate the problem on my machine. Could you please open a ticket with [our support team](https://www.datadoghq.com/support/) referencing this issue ?

Thanks,
Alexandre

**Comment by JosephSpaur** [comment]
@garrardkitchen - did you ever get this working by chance? i'm seeing the same

**Comment by ian28223** [comment]
If you are logging via HTTP `.WriteTo.DatadogLogs` this should be working fine. If you are logging to a file `.WriteTo.File` and having Datadog Agent read the resulting JSON logs, make sure use `JsonFormatter(renderMessage: true)` or `RenderedCompactJsonFormatter()`

**Comment by ogaca-dd** [comment]
Hi @garrardkitchen,

Do you still have the issue?

**Comment by ogaca-dd** [comment]
Hi @garrardkitchen,

Thanks for your quick answer.
