### ISSUE TITLE
restrictedToMinimumLevel arg not supported

### ISSUE THREAD

**Issue by LimeyChris** [DataDog/serilog-sinks-datadog-logs#32]
When using other sinks, such as the file sink, we can override the default minimum logging level on a sink by sink basis using the "restrictedToMinimumLevel" arg. The DatadogLogs sink does not seem to support this option. As an example (json configuration):

{
	"Name": "DatadogLogs",
	"Args": {
		"apiKey": "mykey",
		"host": "myhost",
		"source": "serilog",
		"service": "myservice",
		"tags": [ "Environment:myenv", "Tenant:mytenant", "Component:myservice" ],
		"restrictedToMinimumLevel": "Information"
	}
}

Can this be supported?

**Comment by ssemi** [comment]
I looked for this argument at the source code, and this feature was already applied.
If it is set to "logLevel" instead of "restrictedToMinimumLevel", it is applied.

```
"Args": {
          "apiKey": "yourapikey",
          "source": "mysource",
          "host": myhost",
          "service": "myservice",
          "logLevel": "Warning"  // like this
        }
```
I am finished setting and it is working fine.
