### ISSUE TITLE
Setting in-memory queue limits

### ISSUE THREAD

**Issue by mkromkamp** [DataDog/serilog-sinks-datadog-logs#38]
The [PeriodicBatchSink](https://github.com/serilog/serilog-sinks-periodicbatching/blob/v2.2.0/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L55) used to implement the [DatadogSink.cs](https://github.com/DataDog/serilog-sinks-datadog-logs/blob/master/src/Serilog.Sinks.Datadog.Logs/Sinks/Datadog/DatadogSink.cs#L17) provides the option to specify the limits of the BoundedConcurrentQueue.

However, when configuring the Datadog sink I don't see any corresponding setting that reflects this. Is there any way to specify the log queue size that is kept in memory?

**Comment by benfoster** [comment]
@mkromkamp I've raised a PR [here](https://github.com/DataDog/serilog-sinks-datadog-logs/pull/41)

**Comment by ogaca-dd** [comment]
[Serilog.Sinks.Datadog.Logs 0.3.2](https://www.nuget.org/packages/Serilog.Sinks.Datadog.Logs/0.3.2) should fix the issue: See https://github.com/DataDog/serilog-sinks-datadog-logs/pull/41.
