### ISSUE TITLE
Runtime failures when used from a .NETstandard 2.0 library and Framework host

### ISSUE THREAD

**Issue by ransagy** [DataDog/serilog-sinks-datadog-logs#39]
Due to how the NuGet package is structured right now, This package is unusable with .NET 4.6.x and above hosts.

In my scenario, This package is used inside of a .netstandard 2.0 library that abstracts logging for all my app(s).
This library is then used (as a package as well) by various apps and hosts - Some are .NET Core based, some are .NET Framework based (all 4.7.2).

The 4.7.2 hosts throw a runtime error on missing methods due to the fact of how NuGet resolution works - They get the binary of the net45 target in the package while the compiled code targetted the netstandard2.0 one (specifically, the lack of `Microsoft.Extensions.Options.ConfigurationExtensions` throws it off).

Possible solutions im aware of: either removing the net45 target (thus losing compatibility to older frameworks) or publishing a separate package that only has the .netstandard2.0 target.
There might also be an option to publish an additional net462/net47 target that will use the MS extension library (as they support the netstandard2.0 target there) and allow maintaining wider compatibility.

**Comment by ransagy** [comment]
I went ahead and submitted a PR with the latter approach that fixes the issue for me. Feel free to review and revise.

**Comment by IrisClasson** [comment]
Any update on this?

**Comment by ransagy** [comment]
Sadly no official response to the PR or this so far. We've been using a nuget made from the fork in that PR so far and had no issues.

**Comment by TheMirzai** [comment]
Can confirm we've had the same issue and the mentioned PR fixed it for us. This really needs to be merged back, hopefully soon.

**Comment by ransagy** [comment]
I've updated the PR and awaiting re-review.

**Comment by ogaca-dd** [comment]
[Serilog.Sinks.Datadog.Logs 0.3.4](https://www.nuget.org/packages/Serilog.Sinks.Datadog.Logs/0.3.4) solves the issue.
