### ISSUE TITLE
How to use serilog datadog log for xamarin android and iOS app

### ISSUE THREAD

**Issue by PrachiKarapurkar** [DataDog/serilog-sinks-datadog-logs#47]
I want to use serilog datadog log for logging events on xamarin android and iOS app. How can we use datadog in xamarin. 
How we have to configure datadog configuration for app and how to use log.Information to log data.

**Comment by PrachiKarapurkar** [comment]
I got the solution

**Comment by KBAlphaZA** [comment]
Hi @PrachiKarapurkar , whats the solution or approach ? If you don't mind sharing

**Comment by racins4** [comment]
@PrachiKarapurkar - would you mind sharing your solution for xamarin

**Comment by doiphjeubat** [comment]
@PrachiKarapurkar can you sharing your solution?
