### ISSUE TITLE
Setting DataDog URL via JSON Settings

### ISSUE THREAD

**Issue by MadEddieFFS** [DataDog/serilog-sinks-datadog-logs#48]
I already use the JSON configuration when initializing datadog however I can't see how to set the URL within those JSON settings...The examples on the site show how to do each of these seperately

**Comment by ogaca-dd** [comment]
@MadEddieFFS ,

You can set the Datadog URL  by adding ` "configuration": { "Url": "https://http-intake.logs.datadoghq.com"   }` in the JSON settings.

The field `configuration` is mapped to an object of type [DatadogConfiguration]( https://github.com/DataDog/serilog-sinks-datadog-logs/blob/master/src/Serilog.Sinks.Datadog.Logs/Sinks/Datadog/DatadogConfiguration.cs).

Here is a full example:  

```
"Serilog": {
  "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Datadog.Logs" ],
  "MinimumLevel": "Debug",
  "WriteTo": [
    { "Name": "Console" },
    {
      "Name": "DatadogLogs",
      "Args": {
        "apiKey": "<API_KEY>",
        "source": "<SOURCE_NAME>",
        "host": "<HOST_NAME>",
        "tags": ["<TAG_1>:<VALUE_1>", "<TAG_2>:<VALUE_2>"],
         "configuration": {
                "Url": "https://http-intake.logs.datadoghq.com"                        
         }
      }
    }
  ],
  "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
  "Properties": {
    "Application": "Sample"
  }
}
```

**Comment by jektvik** [comment]
@ogaca-dd would you want to add this to the main readme.md ? I've burned quite some time first putting the url into the 'host' field, then I've tried mimicing the structure of the configuration object like so:
```
...
                    "tags": ["app_name:customer-provisioning","host:app-service"],
                    "configuration" : {
                        "url": "http-intake.logs.datadoghq.eu", 
                        "port": 443, 
                        "useSSL": true, 
                        "useTCP": true
                    }
...
```
none of which worked, so this is some hard-to-guess transform that's actually required here which would be nice to have documented.

**Comment by gh123man** [comment]
Hi @jektvik - Sure thing. I can take care of this.

**Comment by gh123man** [comment]
Updated readme https://github.com/DataDog/serilog-sinks-datadog-logs/commit/a79ac81f63e2bcddac6b831c50feaa6dc8675058

**Comment by jektvik** [comment]
@gh123man , I think this went a bit sideways. I see you've copied my json into the readme.md but this was actually an example of something that did **not** work for me. What eventually **did** work was 
```
         "configuration": {
                "Url": "https://http-intake.logs.datadoghq.com"                        
         }
```
as in @ogaca-dd 's post.

**Comment by gh123man** [comment]
@jektvik sorry for the confusion. Can you describe what didn't work? I tried this config before updating the readme and all 4 keys are bound to the config correctly. (I also double checked and the keys are case-insensitive). 

Perhaps it didn't work  because `"useTCP": true` was set on a HTTP only endpoint (which while a "valid" config is probably a poor example for the readme since it wont work in practice).
