### ISSUE TITLE
Use error.stack for error stacktraces

### ISSUE THREAD

**Issue by kanadaj** [DataDog/serilog-sinks-datadog-logs#49]
According to the datadog documentation (https://docs.datadoghq.com/logs/log_collection/?tab=http#how-to-get-the-most-of-your-application-logs) DataDog has the designated `error.stack` property for stacktraces along with `error.message` for the exception message, however the serilog logger does not remap to this field automatically.  Since Serilog may be used to write to multiple sinks at the same time, it's undesirable to do this mapping in the Enrich pipeline since that would affect the other sinks as well, so the sink itself should be doing this conversion.

**Comment by kanadaj** [comment]
Ah actually DataDog's own C# pipeline should be responsible for this... I think my data might be lacking a flag for the filter...

**Comment by kanadaj** [comment]
Apparently this is happening because by default the Newtonsoft.Json serializer uses pascal case instead of camel case, so the resulting exception attribute is `Exception`, not `exception`. Datadog's default C# pipeline is case sensitive and defines exception with a lower e.

**Comment by rafjsouza** [comment]
> Apparently this is happening because by default the Newtonsoft.Json serializer uses pascal case instead of camel case, so the resulting exception attribute is `Exception`, not `exception`. Datadog's default C# pipeline is case sensitive and defines exception with a lower e.

Hi, did you find any way to solve this?

**Comment by gh123man** [comment]
`Newtonsoft.Json` has been removed since `0.4.0` and we have added the ability to [fully customize the emitted logs](https://github.com/DataDog/serilog-sinks-datadog-logs#using-a-custom-log-formatter). Let me know if this helps with your problem.

**Comment by rafjsouza** [comment]
I think so, but shouldn't this work by default? Maybe I'm doing something wrong, but I feel that the sink should already do this

**Comment by jszwedko** [comment]
<img width="1042" alt="Screenshot 2024-05-08 at 4 10 18 PM" src="https://github.com/DataDog/serilog-sinks-datadog-logs/assets/316880/e73e9be0-422f-4810-b6bf-6633caf6a7b8">

The default C# pipeline appears to capture both `Exception` and `exception` now. I'll close this, but let me know if it is insufficient for your needs.
