### ISSUE TITLE
Provide an option to handle ingestion failure

### ISSUE THREAD

**Issue by yuwaMSFT2** [DataDog/serilog-sinks-datadog-logs#50]
For applications that want to handle the logs reliably, they need to have a way to know any ingestion failures. In current code base, after the datadog sink retries several times, it gives up and discard the data (with a error tracing). This gives difficulty for the application to handle the error. 

Is it possible to add a callback on ingestion failure?

**Comment by ogaca-dd** [comment]
Hi @yuwaMSFT2 ,

I have opened a new PR: https://github.com/DataDog/serilog-sinks-datadog-logs/pull/51. You can get the list of `LogEvent` that are not sent successfully (`CannotSendLogEventException.LogEvents`).

Does it help you for this issue?

**Comment by yuwaMSFT2** [comment]
Thanks @ogaca-dd! Yes this will help for sure!

**Comment by ogaca-dd** [comment]
[Serilog.Sinks.Datadog.Logs 0.3.3](https://www.nuget.org/packages/Serilog.Sinks.Datadog.Logs/0.3.3) includes https://github.com/DataDog/serilog-sinks-datadog-logs/pull/51 which help in handling ingestion failure.
