### ISSUE TITLE
Default csharp pipeline causes problems in displaying log messages in Log Explorer

### ISSUE THREAD

**Issue by BartoszChrostowski** [DataDog/serilog-sinks-datadog-logs#56]
As for now default pipeline for `csharp` source states:
![image](https://user-images.githubusercontent.com/32818862/101268061-a1266180-375f-11eb-81ea-d9d0630d7d55.png)

Renaming `RenderedMessage`:
`RenameKey(logEventAsDict, "RenderedMessage", "message");`

results in pipeline finding the `MessageTemplate` and displaying it in LogExplorer instead of RenderedMessage.

**Comment by vcaraulean** [comment]
We've seen change in message parsing/display in Datadog, which is not formatting our log messages anymore but displaying the template n the LogExplorer.

![image](https://user-images.githubusercontent.com/138733/101360420-e94b9e00-389d-11eb-8bc6-ca329d9c3c99.png)

We're investigating what might be causing this problem. Is this issue directly related to behavior we're observing?

**Comment by vcaraulean** [comment]
Another thing I noticed - in the log entry details we don't even see the `MessageTemplate` property anymore.

**Comment by BartoszChrostowski** [comment]
> We've seen change in message parsing/display in Datadog, which is not formatting our log messages anymore but displaying the template n the LogExplorer

Yes, u can fix it by turning off the default pipeline for `csharp` source.

> Another thing I noticed - in the log entry details we don't even see the `MessageTemplate` property anymore.

Yes. `MessageTemplate` is reinterpreted as `message` (and overrides the `RenderedMessage` which is remapped to `message`) that's why you can not see it. It is the message displayed in LogExplorer.

**Comment by BartoszChrostowski** [comment]
As for now the default pipeline for `csharp` states:

![image](https://user-images.githubusercontent.com/32818862/101680772-79861080-3a61-11eb-9e5d-3701d0715c71.png)

The highlighted step is responsible for overriding explained above.

If you don't want to turn off the default pipeline (`Logs/Configuration/Pipelines`) you applying the patch from #57 will solve the issue

**Comment by vcaraulean** [comment]
> Yes, u can fix it by turning off the default pipeline for csharp source.

Well, we're out of luck - it's the "enterprise"'s configuration that we don't have access to.

What is the expectation for approving the PR and get it fixed in the library? Is anything else missing from it? Or, is it a breaking change that needs more thought?

We could make a fork and apply the patch but for the ~10 of apps we have it will be a long way to go with a forked repo, custom package & our own nuget feed...

**Comment by BartoszChrostowski** [comment]
> What is the expectation for approving the PR and get it fixed in the library? Is anything else missing from it? Or, is it a breaking change that needs more thought?

Don't really know. It is a breaking change because if somebody has the pipeline turned off it will break the logs for them.

Another way around it is changing `source` in the configuration of the app (the default is `csharp`) to something else.
It may cause some problems in your logging system if you are relying on this tag, but if not it will solve the issue.

**Comment by BartoszChrostowski** [comment]
Updated my merge request so that it no longer breaks compatibility and lets users decide whether to map properties.
Hope @ogaca-dd will accept

**Comment by jszwedko** [comment]
<img width="1049" alt="Screenshot 2024-05-09 at 2 29 26 PM" src="https://github.com/DataDog/serilog-sinks-datadog-logs/assets/316880/ac18c9e4-43f3-4ed9-a873-041205c27be5">

The default c# pipeline appears to use `message` now if set.
