### ISSUE TITLE
Possibility to add top-level property and not within "Properties"

### ISSUE THREAD

**Issue by Kiechlus** [DataDog/serilog-sinks-datadog-logs#77]
Right now, the logs look as in the following screenshot.

- All properties by the application are within the "Properties" section
- Is it somehow possible to put certain properties on top-level
- We would need that for the `CorrelationId`

![image](https://user-images.githubusercontent.com/9875731/158990510-83cd1966-f174-43e3-82d7-9cbb38f6b053.png)

**Comment by gh123man** [comment]
You can now do this by supplying a custom `ITextFormatter` with https://github.com/DataDog/serilog-sinks-datadog-logs/pull/86 in `v0.4.0`. There is an example in the readme.
