### ISSUE TITLE
Provide response object in exception

### ISSUE THREAD

**Issue by cdhunt** [DataDog/serilog-sinks-datadog-logs#94]
I'm experiencing the `Coud not send payload to Datadog` exception, but with just the payload included in the exception, I have no idea why delivery is failing. Could you add more information to the message thrown?

https://github.com/DataDog/serilog-sinks-datadog-logs/blob/cf48ff8d9c495b8cff1920ff128ec27ada9a5567/src/Serilog.Sinks.Datadog.Logs/Sinks/Datadog/DatadogHttpClient.cs#L103

**Comment by gh123man** [comment]
Hi @cdhunt Thanks for the feedback.
I'll work on improving this error. Will probably include the last exception thrown from the retry loop.

**Comment by cdhunt** [comment]
I'm digging in a little more and the issue I'm hitting is `result == null` so there is no inner exception.
